apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system

  # Add infrastructure if you have it
  # - ../../infrastructure

  # Add the apps folder (correct path!)
  - ../../apps
